### ISSUE TITLE
read_array_from_csv: allow header rows

### ISSUE THREAD

**Issue by muellerflorian** [fish-quant/big-fish#33] opened 2020-10-14 11:03 UTC
Might be useful to permit header rows in the results files when read from a csv file  (to indicate what the columns contain) . To read those, a slight modification in the function would be sufficient, by allowing access to the `skiprows` parameter of `numpy.loadtext`.

**Comment by Henley13** [comment] 2022-02-06 00:04
If you want the values and the column name you can use `stack.read_dataframe_from_csv`. If you want to skip the header, it's a duplicate of #51. Thus, I close the issue :)

**Closed by Henley13** 2022-02-06 00:04 UTC
Labels: enhancement
